// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers



struct METHOD_TYPE_SecondAgent_Say { };
template<> inline void SecondAgent::_Execute_Method_<METHOD_TYPE_SecondAgent_Say>(behaviac::string p0)
{
	this->SecondAgent::Say(p0);
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
