// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "SecondAgent.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

SecondAgent::SecondAgent()
{
	m_Targets.push_back("");
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR
	m_Targets.push_back("小明");
	m_Targets.push_back("小红");
	m_Targets.push_back("小军");
	m_Targets.push_back("小五郎");
///<<< END WRITING YOUR CODE
}

SecondAgent::~SecondAgent()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}

behaviac::string SecondAgent::RandomTarget()
{
///<<< BEGIN WRITING YOUR CODE RandomTarget
	if (m_Targets.size() == 0)
		return "";

	int x = Rand_int(int(0), int(m_Targets.size())-1);
	return m_Targets.at(x);
///<<< END WRITING YOUR CODE
}

void SecondAgent::Say(behaviac::string msg)
{
///<<< BEGIN WRITING YOUR CODE Say
	std::cout << UTF8ToGBK(msg).c_str() << std::endl;
///<<< END WRITING YOUR CODE
}

void SecondAgent::SayTo(behaviac::string name, behaviac::string msg)
{
///<<< BEGIN WRITING YOUR CODE SayTo
	std::cout << "我对" << name << "说 : " << UTF8ToGBK(msg).c_str() << std::endl;
///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE
